### ISSUE TITLE
Mongodb 常用命令（一）

### ISSUE THREAD

**Issue by lyne007** [lyne007/blog#20]
- 安装mongodb服务

1. 先到官网下载压缩包 mongod.tgz 。 
2. 解压到当前目录:
 `tar -xvf mongodb.tgz`
3. 移动解压后的文件夹到指定的目录中:
`mv mongodb /usr/local/mongodb`
4. 新建几个目录，分别用来存储数据和日志:
```
#数据存储目录
mkdir -p /usr/local/mongodb/single/data/db 
#日志存储目录
mkdir -p /usr/local/mongodb/single/log
```
5. 新建并修改配置文件
`vi /usr/local/mongodb/single/mongod.conf`
配置文件的内容如下:
```
systemLog:
    #MongoDB发送所有日志输出的目标指定为文件
    # #The path of the log file to which mongod or mongos should send all diagnostic logging information 
    destination: file
    #mongod或mongos应向其发送所有诊断日志记录信息的日志文件的路径
    path: "/usr/local/mongodb/single/log/mongod.log" #当mongos或mongod实例重新启动时，mongos或mongod会将新条目附加到现有日志文件的末尾。
    logAppend: true
storage:
    #mongod实例存储其数据的目录。storage.dbPath设置仅适用于mongod。
    ##The directory where the mongod instance stores its data.Default Value is "/data/db". 
    dbPath: "/usr/local/mongodb/single/data/db"
    journal:
        #启用或禁用持久性日志以确保数据文件保持有效和可恢复。
         enabled: true
processManagement:
    #启用在后台运行mongos或mongod进程的守护进程模式。
    fork: true
net:
    #服务实例绑定的IP，默认是localhost 
    bindIp: localhost,127.0.0.1
    #bindIp #绑定的端口，默认是27017 
    port: 27017

```
- 启动mongodb服务
`/usr/local/mongodb/bin/mongod -f /usr/local/mongodb/single/mongod.conf -auth`  # `-auth 启用认证`

- 连接mongodb
`mongo  --host=127.0.0.1  --port=27017`
- 创建管理员用户
```
>  use admin
>  db.createUser({user:"root",pwd:"123456",roles:["root"]})
```
- 验证身份
`>  db.auth("root","123456")`

集合名称：comment

- 选择切换数据库:
`use articledb`
- 创建一个集合
`db.createCollection("comment")`
- 插入数据:
`db.comment.insert({bson数据})`
- 查询所有数据:
`db.comment.find()`
- 条件查询数据:
`db.comment.find({条件})`
- 查询符合条件的第一条记录:
`db.comment.findOne({条件}) `
- 查询符合条件的前几条记录:
`db.comment.find({条件}).limit(条数) `
- 查询符合条件的跳过的记录:
`db.comment.find({条件}).skip(条数) `
- 修改数据:
`db.comment.update({条件},{修改后的数据}) 或db.comment.update({条件},{$set:{要修改部分的字段:数据}) `
- 修改数据并自增某字段值:
`db.comment.update({条件},{$inc:{自增的字段:步进值}}) `
- 删除数据:
`db.comment.remove({条件})`
- 统计查询:
`db.comment.count({条件})`
- 模糊查询:
`db.comment.find({字段名:/正则表达式/})`
- 条件比较运算:
`db.comment.find({字段名:{$gt:值}}) `
- 包含查询:
`db.comment.find({字段名:{$in:[值1，值2]}})或db.comment.find({字段名:{$nin:[值1，值2]}})`
- 条件连接查询:
`db.comment.find({$and:[{条件1},{条件2}]})或db.comment.find({$or:[{条件1},{条件2}]})`
- 查看索引：
`db.comment.getIndexes()`
- 创建索引
`db.comment.createIndex(keys, options)` 
-- 普通索引（单字段）：
例：`db.comment.createIndex({userid:1})`，`db.comment.createIndex({userid:1},{unique:true})`
-- 复合索引（多字段）：
例：`db.comment.createIndex({userid:1, age: -1})`
- 移除索引
`db.comment.dropIndex(index)`  
例：根据条件移除：`db.collection.dropIndex({userid:1})`，根据索引名移除：`db.collection.dropIndex("userid_1")`
- 执行计划
` db.collection.find(query,options).explain(options)`
例：`db.comment.find({userid:"1"}).explain()`   // explain查看是否使用到索引
- 涵盖查询
`db.comment.find({userid:"1"},{userid:1,_id:0})`   // 查询的userid已经在索引的集合中，所以不需要再根据索引值查询集合，效率大大提升
<img width="527" alt="图片" src="https://user-images.githubusercontent.com/28702327/122181892-5890f300-cebc-11eb-8ad8-e895f00d89a0.png">
